sudo: required
services:
  - docker

before_install:
  - docker build -t mpltr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mpltr/react-test npm test

after_success:
  - docker build -t mpltr/multi-client ./client
  - docker build -t mpltr/multi-nginx ./nginx
  - docker build -t mpltr/multi-server ./server
  - docker build -t mpltr/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push mpltr/multi-client
  - docker push mpltr/multi-nginx
  - docker push mpltr/multi-server
  - docker push mpltr/multi-worker
  # do something else
# deploy:
#   provider: elasticbeanstalk
#   region: 'us-west-2'
#   app: 'multi-docker'
#   env: 'MultiDocker-env'
#   bucket_name: 'elasticbeanstalk-us-west-2-553690235482'
#   bucket_path: 'docker-multi'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
  # secret_access_key: $AWS_SECRET_KEY